name: VirtualChest
version: '${project.version}'
main: com.comonier.virtualchest.Main
api-version: "1.21"
folia-supported: true
description: A high-performance virtual chest system with SQL/MySQL support.
author: Comonier

commands:
  pv:
    description: Open a Virtual Chest.
    usage: /pv <number>
    permission: virtualchest.use
    aliases: [vc, virtualchest]

permissions:
  virtualchest.use:
    description: Basic permission to use the virtual chest system.
    default: true
  virtualchest.admin:
    description: Allows inspecting other players and reloading the plugin.
    default: op
  virtualchest.*:
    description: Grant all VirtualChest permissions.
    children:
      virtualchest.use: true
      virtualchest.admin: true
